version: "3.8"

services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: slick
      POSTGRES_PASSWORD: p455w0rd
      POSTGRES_DB: akka-stream-http-slick

volumes:
  postgres:
